name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # execute diariamente à meia-noite
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # para definir a saída do gráfico gerado (opcional)
          # output: "path/to/output.svg"

      - name: Push the Snake Game
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true
          # para definir o caminho do arquivo (opcional)
          # path: path/to/output.svg
