name: Update README

on:
  schedule:
    - cron: '0 * * * *' # Atualiza a cada hora
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate GitHub Stats
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          curl -o README.md "https://github-readme-stats.vercel.app/api?username=antoni0neto&count_private=true&show_icons=true&theme=radical"
          curl -o languages.md "https://github-readme-stats.vercel.app/api/top-langs/?username=antoni0neto&count_private=true&layout=compact&theme=radical"
      - name: Append Languages to README
        run: |
          echo '' >> README.md
          cat languages.md >> README.md
      - name: Commit and Push if Changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update GitHub stats and languages"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
